In [10]:

import sys
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_79f85d76e1904d5d921fc81515ec8cd8 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='Rj9NydkrKv2oRQHqn5PY_O7IOO0WzZ16tPiKTWk4QKpk',
    ibm_auth_endpoint="https://iam.ng.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_79f85d76e1904d5d921fc81515ec8cd8.get_object(Bucket='test1a5c9d6b4dbc44121a156ee076604cae9',Key='Gold_Price_2005_2018.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_1 = pd.read_csv(body)
df_data_1.head()

,Instrument Type,Date,Traded Contract(Lots),Quantity (000's),Total Value (Lacs)
0,FUTCOM,02 May 2005,5240,5240,32471.98
1,FUTCOM,03 May 2005,5306,5306,32691.64
2,FUTCOM,04 May 2005,3559,3559,21956.48
3,FUTCOM,05 May 2005,5219,5219,32199.49
4,FUTCOM,06 May 2005,8610,8610,52757.60

In [11]:
df_data_1.drop(['Instrument Type','Date'],1,inplace=True)
df_data_2=df_data_1.dropna()
df_data_2.head()

   Traded Contract(Lots)  Quantity (000's)  Total Value (Lacs)
0                   5240              5240            32471.98
1                   5306              5306            32691.64
2                   3559              3559            21956.48
3                   5219              5219            32199.49
4                   8610              8610            52757.60

In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

x=df_data_1.values[:,0:2]
y=df_data_1.values[:,2]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state= 100)
#(criterion='entropy',random_state= 100)
print(len(x_train))
print(len(y_train))
print(len(x_test))
print(len(y_test))
model_gold=LinearRegression()
model_gold.fit(x_train,y_train)

2747
2747
1178
1178

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [13]:
y_pred = model_gold.predict(x_test)
print(y_pred)

[   34795.88395293   854274.07966925   268477.95917729 ...,
   855587.5238856    169507.16259319  1257482.95487429]

In [15]:
print("Accuracy: ", r2_score(y_test,y_pred)*100)

Accuracy:  66.8103117474